[theme]
primaryColor       = "#BD866A"
backgroundColor    = "#1a1512"
secondaryBackgroundColor = "#221c18"
textColor          = "#F4ECDC"
font               = "sans serif"

[server]
headless = true
runOnSave = true
maxUploadSize = 20
